name: zap-scan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  zapscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "https://example.com"
          cmd_options: "-a"
          allow_issue_writing: false

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zapscan
          path: report.html
