
name: Semgrep Static Scan

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container: semgrep/semgrep:latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v6

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config p/ci \
            --config p/security-audit \
            --config p/secrets \
            --verbose \
            --max-target-bytes 0 \
            --no-git-ignore \
            --metrics off \
            --sarif --output semgrep.sarif

      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@v5
        with:
          name: semgrep-sarif
          path: semgrep.sarif


